# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-internal_affairs
  - rubocop-minitest

require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Minitest:
  Include:
    - lib/rubocop/minitest/assert_offense.rb

InternalAffairs/NodeMatcherDirective:
  Enabled: false

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Naming/InclusiveLanguage:
  Enabled: true
  CheckStrings: true
  FlaggedTerms:
    ' a offense':
      Suggestions:
        - an offense
    auto-correct:
      Suggestions:
        - autocorrect
    auto_correct:
      Suggestions:
        - autocorrect
    behaviour:
      Suggestions:
        - behavior
    offence:
      Suggestions:
        - offense
    does_not_registers:
      Suggestions:
        - does_not_register

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*
    - tasks/changelog.rb

Metrics/MethodLength:
  CountAsOne: ['heredoc']

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_class_methods
    - initializer
    - instance_methods
    - protected_methods
    - private_methods

Layout/RedundantLineBreak:
  Enabled: true

# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'test/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'rubocop-minitest.gemspec'

Naming/FileName:
  Exclude:
    - lib/rubocop-minitest.rb

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*.rb'

Performance/StringIdentifierArgument:
  Exclude:
    - 'test/**/*.rb'
